name: percobaan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.6   # <-- Tambahkan ini

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Classic Burger.jpg
    - assets/Double Cheese Burger.jpg
    - assets/Spicy Hotdog Burger.jpg
    - assets/Margherita Pizza.jpg
    - assets/Pepperoni Slice.jpg
    - assets/Salmon Sushi.jpg
    - assets/Sushi Platter.jpg
    - assets/Ramen Spicy.jpg
    - assets/Chicken Ramen.jpg
    - assets/Chocolate Cake.jpg
    - assets/Ice Cream Bowl.jpg
    - assets/Fresh Lemonade.jpg
    - assets/Iced Coffee.jpg
    - assets/Fruit Smoothie.jpg
